name: Python Test Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. This step checks out your repository's code
      #    so the pipeline can see app.py and test_app.py
      - name: Check out code
        uses: actions/checkout@v4

      # 2. This step sets up the Python language on the runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. This step runs our test file using python
      - name: Run tests
        run: python test_app.py

      - name: hello4
        run: ls -la
